name: abd_shop
description: "A new project for online shop in abadeh city!"
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  flutter_localization: ^0.2.0
  smooth_page_indicator: ^1.1.0
  flutter_spinkit: ^5.2.0

  cupertino_icons: ^1.0.2
  bottom_navy_bar: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # Work in this area with "base" branch

  assets:
     - assets/
     - assets/images/
  #   - images/a_dot_ham.jpeg

  fonts:
     - family: Yekan
       fonts:
         - asset: assets/fonts/Yekan.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #