name: abd_shop
description: "A project for online shop in abadeh city!"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #  intl: ^0.19.0
  smooth_page_indicator: ^1.1.0
  flutter_spinkit: ^5.2.0
  cupertino_icons: ^1.0.6
#  bottom_navy_bar: ^6.0.0
  permission_handler: ^11.2.0 # Add this package for the permission handler
  connectivity_plus: ^5.0.2   # Add this package for checking wifi and mobile data connectivity
  http: ^1.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0

#dependency_overrides:
#   intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true

  # Work in this area with "base" branch

  assets:
    - assets/
    - assets/images/
    - assets/fonts/
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Yekan
      fonts:
        - asset: assets/fonts/Yekan.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #